In [ ]:
#Logistic Regression Model Training for Ecommerce Ad Click Prediction

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings('ignore')
import joblib

In [4]:
df=pd.read_csv('/content/drive/MyDrive/AI ENGINEER/AdClick.csv')
df.head(10)

   TimeSpentSeconds  PagesVisited       AdType  Clicked
0         14.078043             4        Adult        0
1         90.303643             2        Adult        0
2         39.502371             7        Adult        1
3         27.388277             9        Adult        1
4          5.088746             6        Adult        0
5          5.087889             5   Commercial        0
6          1.795163             6   Commercial        0
7         60.336926             5        Adult        1
8         27.572465             5  Educational        1
9         36.937502             5        Adult        1

In [5]:
df.isnull().sum()

TimeSpentSeconds    0
PagesVisited        0
AdType              0
Clicked             0
dtype: int64

In [6]:
df.dtypes

TimeSpentSeconds    float64
PagesVisited          int64
AdType               object
Clicked               int64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1334 entries, 0 to 1333
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   TimeSpentSeconds  1334 non-null   float64
 1   PagesVisited      1334 non-null   int64
 2   AdType            1334 non-null   object
 3   Clicked           1334 non-null   int64
dtypes: float64(1), int64(2), object(1)
memory usage: 41.8+ KB

In [8]:
df.describe()

       TimeSpentSeconds  PagesVisited      Clicked
count       1334.000000   1334.000000  1334.000000
mean          30.068417      4.953523     0.373313
std           30.090477      2.109728     0.483866
min            1.000000      1.000000     0.000000
25%            7.962811      3.000000     0.000000
50%           21.055690      5.000000     0.000000
75%           42.193540      6.000000     1.000000
max          245.173368     14.000000     1.000000

In [9]:
df['AdType'].unique()

array(['Adult', 'Commercial', 'Educational', 'Recruitment'], dtype=object)

In [10]:
df['AdType'].value_counts()

AdType
Adult          532
Commercial     401
Educational    276
Recruitment    125
Name: count, dtype: int64

In [11]:
df_Encoded = pd.get_dummies(df, columns=['AdType'], drop_first=True, dtype=int)

In [12]:
df_Encoded.columns
df_Encoded.head()

,TimeSpentSeconds,PagesVisited,Clicked,AdType_Commercial,AdType_Educational,AdType_Recruitment
0,14.078043,4,0,0,0,0
1,90.303643,2,0,0,0,0
2,39.502371,7,1,0,0,0
3,27.388277,9,1,0,0,0
4,5.088746,6,0,0,0,0

In [13]:
X = df_Encoded[['TimeSpentSeconds', 'PagesVisited', 'AdType_Commercial', 'AdType_Educational', 'AdType_Recruitment']]
y=df_Encoded['Clicked']

In [14]:
joblib.dump(X.columns.tolist(), 'feature_names.pkl') #to save features name

['feature_names.pkl']

In [15]:
#Split data in training and testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [16]:
#Scaling data
from sklearn.preprocessing import StandardScaler
Ecommerce_scaler=StandardScaler()
X_train_Scaled=Ecommerce_scaler.fit_transform(X_train)
X_test_Scaled=Ecommerce_scaler.transform(X_test)

In [18]:
#Apply Logistic Regression on Scaled data
L_Regression=LogisticRegression(
    class_weight='balanced', random_state=42
)
L_Regression_Model=L_Regression.fit(X_train_Scaled,y_train)

In [19]:
y_predicted=L_Regression_Model.predict(X_test_Scaled)
y_predicted

array([0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1])

In [20]:
print(y_test,y_predicted)

218     0
1190    1
325     1
305     1
471     0
       ..
606     1
188     1
814     0
136     1
1123    0
Name: Clicked, Length: 267, dtype: int64 [0 0 1 1 1 1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 0 0 0 1 1 1 0 1 0 0
 1 0 1 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 1 1 0 1 0 1 0 0 0 1 1 0 1 0 1
 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 1 0 1 1 0 1 0 0 1 0
 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0
 0 0 0 0 1 0 1 0 0 0 1 1 0 1 1 0 1 1 1 0 0 0 1 0 1 0 0 1 1 1 1 0 0 1 0 1 0
 0 0 1 0 1 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 0 0 0 1 0 0 1 0 0 1 1 1 0 0
 0 1 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 1
 0 0 1 1 0 1 0 1]

In [21]:
L_Regression_Model.score(X_test_Scaled,y_test)

0.6404494382022472

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_predicted)

0.6404494382022472

In [23]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_predicted))

              precision    recall  f1-score   support

           0       0.72      0.69      0.71       167
           1       0.52      0.56      0.54       100

    accuracy                           0.64       267
   macro avg       0.62      0.62      0.62       267
weighted avg       0.65      0.64      0.64       267

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_predicted)

array([[115,  52],
       [ 44,  56]])

In [25]:
print(y.value_counts())

Clicked
0    836
1    498
Name: count, dtype: int64

In [26]:
#Save File and Scaled File
joblib.dump(L_Regression_Model,'ad_click_model.pkl')
joblib.dump(Ecommerce_scaler,'ad_click_scaler.pkl')

['ad_click_scaler.pkl']

In [33]:
%%writefile app.py
import streamlit as st
import joblib
import numpy as np
import pandas as pd

# Load assets
model = joblib.load('ad_click_model.pkl')
scaler = joblib.load('ad_click_scaler.pkl')
feature_names = joblib.load('feature_names.pkl')

# Page Styling
st.set_page_config(
    page_title="Ad Click Prediction",
    page_icon="📈",
    layout="centered"
)


st.title("📊 E-Commerce Ad Click Predictor")
st.markdown("Predict Ad Click Probability ")
st.markdown("---")

# Input Form
st.subheader("📊 Session Information")
time_spent = st.slider("Time Spent on Site (Seconds)", 0, 1200, 200)
pages_visited = st.number_input("Pages Visited during session", min_value=0, max_value=50, value=10)

st.subheader("🏷️ Advertisement Category")
ad_type_selected = st.selectbox("Select Ad Type", ["Adult", "Commercial", "Educational", "Recruitment"])

if st.button("Predict", type="primary"):

    input_dict = {
        'TimeSpentSeconds': time_spent,
        'PagesVisited': pages_visited
    }


    for col in feature_names:
        if col.startswith('AdType_'):
            category_name = col.replace('AdType_', '')
            input_dict[col] = 1 if ad_type_selected == category_name else 0

    # Format to DataFrame
    input_df = pd.DataFrame([input_dict])[feature_names]

    # Predict
    scaled_data = scaler.transform(input_df)
    prediction = model.predict(scaled_data)[0]
    probability = model.predict_proba(scaled_data)[0][1] * 100

    # Show  UI
    st.markdown("---")
    if prediction == 1:
        st.error(f" **High Click Potential!** Probable click conversion detected ({probability:.2f}% confidence).")
    else:
        st.success(f" **Low Click Potential.** High likelihood user will skip this advertisement ({100 - probability:.2f}% confidence).")

Overwriting app.py

In [28]:
#Install Streamlit and Localtunnel
!pip install -q streamlit
!npm install -g localtunnel

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇
changed 22 packages in 2s
⠇
⠇3 packages are looking for funding
⠇  run `npm fund` for details
⠇

In [29]:
# Fetch your Tunnel IP/Password
import urllib.request
print("Your Tunnel Password is:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip())

Your Tunnel Password is: 8.229.97.11

In [30]:
!pip install -q pyngrok

In [31]:
from pyngrok import ngrok

# Authenticate ngrok
ngrok.set_auth_token("3A5yARbs6K7C1YIVAqkcTeddEM9_6U6LGLczfWSQEg3xqiGxc")

In [34]:
import os

# Kill any stuck Streamlit or Tunnel instances
os.system("pkill streamlit")
os.system("pkill ngrok")

# Run Streamlit in the background
os.system("streamlit run app.py &")

# Open Ngrok Tunnel to Port 8501
public_url = ngrok.connect(8501)
print("🚀 Click your fast Streamlit link here:", public_url)

🚀 Click your fast Streamlit link here: NgrokTunnel: "https://stalagmitical-paternally-lailah.ngrok-free.dev" -> "http://localhost:8501"